services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: goga
      - key: N8N_BASIC_AUTH_PASSWORD
        value: 123456
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
